
title: "Etterby Analytics"
description: "Premium, minimal, outcomes-first analytics consulting. Pipelines, metrics, and ML that ship and stick."
url: "https://etterby.com"  # set to https://etterby.com when live
baseurl: ""  # set to /analytics only if using subpath
google_analytics:
  measurement_id: G-8T9EL4DVTW
markdown: kramdown
theme: null
plugins: []
collections:
  work:
    output: true
    permalink: /work/:name/
  services:
    output: true
    permalink: /services/:name/
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "work"
    values:
      layout: case
  - scope:
      path: ""
      type: "services"
    values:
      layout: service
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default

company:
  name: "Etterby Analytics Ltd"
  legal_name: "Etterby Analytics Ltd"
  url: "https://etterby.com"
  email: "hello@etterby.com"
  description: "Independent analytics consultancy delivering data platforms, experimentation, and forecasting."
  logo: "/assets/og-image.png"
  same_as:
    - "https://www.linkedin.com/company/etterby-analytics/"
  address:
    street_address: "Remote-first"
    address_locality: "London"
    address_region: "England"
    postal_code: ""
    address_country: "GB"
  founder: "Founder-led analytics team"
