
title: "Etterby Analytics"
description: "Premium, minimal, outcomes-first analytics consulting. Pipelines, metrics, and ML that ship and stick."
url: ""  # set to https://etterby.com when live
baseurl: ""  # set to /analytics only if using subpath
markdown: kramdown
theme: null
plugins: []
collections:
  work:
    output: true
    permalink: /work/:name/
  services:
    output: true
    permalink: /services/:name/
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "work"
    values:
      layout: case
  - scope:
      path: ""
      type: "services"
    values:
      layout: service
